### ISSUE TITLE
有没有类似管理员权限的方式管理密码

### ISSUE THREAD

**Issue by KEVIN-G386** [s0urcelab/serverless-cloud-notepad#10]
项目使用感觉很好,但是请问如果有人恶意设置密码或者修改密码怎么解决,如果重新部署数据都消失了. 
我的想法是增加一个pwd的环境变量,使用这个pwd作为root密码,无论什么密码 认证时输入pwd就直接通过

**Comment by s0urcelab** [comment]
对于服务的搭建者/拥有者，始终可以直接去cloudflare后台编辑kv数据库，能复制/修改内容，也可以删除。
好像没有太大必要为了这个单独写个逻辑？

**Comment by KEVIN-G386** [comment]
> 对于服务的搭建者 / 拥有者，始终可以直接去 cloudflare 后台编辑 kv 数据库，能复制 / 修改内容，也可以删除。 好像没有太大必要为了这个单独写个逻辑？

我没有在kv中找到密码管理，但确实有内容，如果是这样的话，那确实不用了
