### ISSUE TITLE
preview_id 这个要不要填

### ISSUE THREAD

**Issue by E2077** [s0urcelab/serverless-cloud-notepad#13]
大佬，新版的 preview_id这个我删掉有影响吗
kv_namespaces = [
{ binding = "NOTES", id = "b3afc649c15247c9962346b3de4730cc", preview_id = "01083e57f68046079a62015c3ea4a145" },
{ binding = "SHARE", id = "c075feeec9b6414296e6a3df7404e6a8", preview_id = "f89caa54860940709800dc6ed3ff920a" }
]
我填写的是
kv_namespaces = [
{ binding = "NOTES", id = "我的ID" },
{ binding = "SHARE", id = "我的ID2" }
]
preview_id这个没说明我就没有填写了

**Comment by s0urcelab** [comment]
中文版本在另一个分支，自己fork之后稍微改一下也可以，反正没几个字

**Comment by E2077** [comment]
> 中文版本在另一个分支，自己fork之后稍微改一下也可以，反正没几个字

好的，谢谢大佬，新版的 preview_id这个我删掉有影响吗
kv_namespaces = [
  { binding = "NOTES", id = "b3afc649c15247c9962346b3de4730cc", preview_id = "01083e57f68046079a62015c3ea4a145" },
  { binding = "SHARE", id = "c075feeec9b6414296e6a3df7404e6a8", preview_id = "f89caa54860940709800dc6ed3ff920a" }
]
我填写的是
kv_namespaces = [
  { binding = "NOTES", id = "我的ID" },
  { binding = "SHARE", id = "我的ID2" }
]
preview_id这个没说明我就没有填写了
