### ISSUE TITLE
Hello, can the project be deployed using Wrangler?

### ISSUE THREAD

**Issue by ghost** [s0urcelab/serverless-cloud-notepad#20]
I don't seem to understand the current deployment method, or can I directly provide the compiled files?

**Comment by s0urcelab** [comment]
Yes, you can!

But you need edit some code before you run `wrangler publish`:

- Create 2 KV in your Cloudflare dashboard,  replace the values below with your new KV id: 
https://github.com/s0urcelab/serverless-cloud-notepad/blob/441fabf22de4ec469ee2d1e1db9fe75f617a4dea/wrangler.toml#L6
https://github.com/s0urcelab/serverless-cloud-notepad/blob/441fabf22de4ec469ee2d1e1db9fe75f617a4dea/wrangler.toml#L7

- Change the two values below to any **string** you like (Don't forget add ""):
https://github.com/s0urcelab/serverless-cloud-notepad/blob/441fabf22de4ec469ee2d1e1db9fe75f617a4dea/src/constant.js#L5
https://github.com/s0urcelab/serverless-cloud-notepad/blob/441fabf22de4ec469ee2d1e1db9fe75f617a4dea/src/constant.js#L7
