### ISSUE TITLE
敏感词提示

### ISSUE THREAD

**Issue by miantiao-me** [s0urcelab/serverless-cloud-notepad#24]
我之前也有这个想法，做类似的工具，但是被敏感词劝退了。

我试了一下你也没做，是否考虑下    https://note.src.moe/share/89afacb06caf3135bc6d1ccb95d4dca7

**Comment by s0urcelab** [comment]
> 我之前也有这个想法，做类似的工具，但是被敏感词劝退了。
> 
> 我试了一下你也没做，是否考虑下 https://note.src.moe/share/89afacb06caf3135bc6d1ccb95d4dca7

所以推荐自建，我域名上部署的这个仅作演示。
（其实真要做敏感词过滤也可以做，但是对于这种业务代码都没几行的项目，感觉有点本末倒置了
