### ISSUE TITLE
求助：可以仅仅在网页部署，而不是在wrangler CLI部署吗

### ISSUE THREAD

**Issue by XCQ0607** [s0urcelab/serverless-cloud-notepad#7]
因为本人是初级小白，如果能更新更详细的部署教程就再好不过了。

希望可以更新一下部署方式哦

感谢！！！！

**Comment by XCQ0607** [comment]
我是使用pages部署的，构建命令也没有填写
相关部署信息
![459118f1-e09b-4761-8345-fed8a28585f0](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/28f98ab3-72ac-43f9-96b7-c819c11a728d)
![52bdd6f3-598b-4fc9-9e8f-9056c916c3c3](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/40d8fa42-2de3-4c0f-8a62-1e32617646ba)
![40ce512d-4156-424a-8fd6-aad567ff4468](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/df97359f-462a-4448-b8b2-fdd938ede952)
![1bebeba6-7cd4-4d18-b5a0-16a6a370958c](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/bcc06553-dda4-420e-8e3f-ffd249ab5a41)
然后它就是这样的
![436cffe5-1dd3-4eab-84e1-952e01bb5d5a](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/8e41a159-00f3-482b-8c8a-6c1192788710)
部署页面长这样的
![44e8a93c-93eb-4033-8f88-a256d998dd78](https://github.com/s0urcelab/serverless-cloud-notepad/assets/125746521/908522d0-32d6-402a-abc1-0d5f7abb4911)

**Comment by s0urcelab** [comment]
@XCQ0607 已支持一键部署，参见文档部署章节，欢迎体验
